=== folio-org/mod-circulation/ramls/renew-by-barcode-request.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "description": "Request to renew an existing loan, found by barcodes of item and loanee",
  "properties": {
    "itemBarcode": {
      "description": "Barcode of the item to be renewed",
      "type": "string"
    },
    "userBarcode": {
      "description": "Barcode of the user (representing the patron) the item has been loaned to",
      "type": "string"
    },
    "servicePointId": {
      "description": "Service point where an item is being processed",
      "type": "string",
      "pattern": "^[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}$"
    },
    "overrideBlocks": {
      "description": "Blocks to override",
      "$ref": "override-blocks.json"
    }
  },
  "additionalProperties": false,
  "required": [
    "itemBarcode",
    "userBarcode"
  ]
}

=== folio-org/mod-circulation/ramls/examples/renew-by-barcode-request.json
{
  "userBarcode": "466983136459401",
  "itemBarcode": "2887532577331",
  "servicePointId":"7c5abc9f-f3d7-4856-b8d7-6712462ca007",
  "overrideBlocks": {
    "patronBlock": {},
    "renewalBlock":{},
    "renewalDueDateRequiredBlock":{
      "dueDate":"2021-05-31T12:53:00Z"
    },
    "comment": "Comment"
  }
}
